apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openalgo.fullname" . }}
  labels:
    app: {{ include "openalgo.name" . }}
    chart: {{ include "openalgo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "openalgo.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "openalgo.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: openalgo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: {{ include "openalgo.fullname" . }}-secret
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources: {}
