apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openalgo.fullname" . }}
  labels:
    app: {{ include "openalgo.name" . }}
    chart: {{ include "openalgo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "openalgo.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "openalgo.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      {{- end }}
      volumes:
        - name: env-file
          configMap:
            name: {{ include "openalgo.fullname" . }}-env
      {{- if .Values.persistentVolume.pvcEnabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "openalgo.fullname" . }}-data
      {{- end }}
      containers:
        - name: openalgo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.securityContext.enabled }}
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          {{- end }}
          ports:
            - containerPort: 5000
            - containerPort: 8765
          envFrom:
            - secretRef:
                name: {{ include "openalgo.fullname" . }}-secret
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources: {}
          volumeMounts:
            - name: env-file
              mountPath: /app/.env
              subPath: .env
          {{- if .Values.persistentVolume.pvcEnabled }}
            - name: data
              mountPath: {{ .Values.persistentVolume.mountPath | quote }}
          {{- end }}
