{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "openalgo.fullname" . }}
  labels:
    app: {{ include "openalgo.name" . }}
    chart: {{ include "openalgo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- if eq .Values.ingress.controller "traefik" }}
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.rule: Host(`{{ .Values.openalgoPublicUrl }}`)
    traefik.ingress.kubernetes.io/router.middlewares: ""
    {{- else if eq .Values.ingress.controller "nginx" }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
spec:
  rules:
    - host: {{ .Values.openalgoPublicUrl }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "openalgo.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
