apiVersion: v1
kind: Service
metadata:
  name: {{ include "openalgo.fullname" . }}
  labels:
    app: {{ include "openalgo.name" . }}
    chart: {{ include "openalgo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
    - name: ws
      port: 8765
      targetPort: 8765
      protocol: TCP
  selector:
    app: {{ include "openalgo.name" . }}
    release: {{ .Release.Name }}
