{{- if and .Values.ingress.enabled (eq .Values.ingress.controller "traefik") }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "openalgo.fullname" . }}-strip-ws
spec:
  stripPrefix:
    prefixes:
      - /ws
{{- end }}
