apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openalgo.fullname" . }}-secret
  labels:
    app: {{ include "openalgo.name" . }}
    chart: {{ include "openalgo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
