image:
  repository: sudhan/openalgo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

openalgoPublicUrl: "openalgo.mydomain.com"
ingress:
  enabled: true
  controller: traefik # Options: traefik, nginx

secretEnv:
  BROKER_API_KEY: ""
  BROKER_API_SECRET: ""
  BROKER_API_KEY_MARKET: ""
  BROKER_API_SECRET_MARKET: ""
  APP_KEY: ""
  API_KEY_PEPPER: ""

env:
  # Broker Configuration
  REDIRECT_URL: "http://127.0.0.1:5000/<broker>/callback"
  VALID_BROKERS: "fivepaisa,fivepaisaxts,aliceblue,angel,compositedge,dhan,dhan_sandbox,firstock,flattrade,fyers,groww,ibulls,iifl,kotak,jainam,jainampro,paytm,pocketful,shoonya,tradejini,trustline,upstox,wisdom,zebu,zerodha"

  # Database Configuration
  DATABASE_URL: "sqlite:////data/db/openalgo.db"
  LATENCY_DATABASE_URL: "sqlite:////data/db/latency.db"
  LOGS_DATABASE_URL: "sqlite:////data/db/logs.db"

  # Ngrok/Host Configuration
  NGROK_ALLOW: "FALSE"
  HOST_SERVER: "http://127.0.0.1:5000"

  # Flask App Config
  FLASK_HOST_IP: "127.0.0.1"
  FLASK_PORT: "5000"
  FLASK_DEBUG: "False"
  FLASK_ENV: "development"

  # WebSocket Config
  WEBSOCKET_HOST: "localhost"
  WEBSOCKET_PORT: "8765"
  WEBSOCKET_URL: "ws://localhost:8765"

  # ZeroMQ Config
  ZMQ_HOST: "localhost"
  ZMQ_PORT: "5555"

  # Logging
  LOG_TO_FILE: "False"
  LOG_LEVEL: "INFO"
  LOG_DIR: "log"
  LOG_FORMAT: "[%(asctime)s] %(levelname)s in %(module)s: %(message)s"
  LOG_RETENTION: "14"
  LOG_COLORS: "True"
  FORCE_COLOR: "1"

  # Rate Limiting
  LOGIN_RATE_LIMIT_MIN: "5 per minute"
  LOGIN_RATE_LIMIT_HOUR: "25 per hour"
  API_RATE_LIMIT: "10 per second"
  ORDER_RATE_LIMIT: "10 per second"
  SMART_ORDER_RATE_LIMIT: "2 per second"
  WEBHOOK_RATE_LIMIT: "100 per minute"
  STRATEGY_RATE_LIMIT: "200 per minute"
  RESET_RATE_LIMIT: "15 per hour"

  # API Config
  SMART_ORDER_DELAY: "0.5"
  SESSION_EXPIRY_TIME: "03:00"

  # CORS Config
  CORS_ENABLED: "TRUE"
  CORS_ALLOWED_ORIGINS: "http://127.0.0.1:5000"
  CORS_ALLOWED_METHODS: "GET,POST,DELETE,PUT,PATCH"
  CORS_ALLOWED_HEADERS: "Content-Type,Authorization,X-Requested-With"
  CORS_EXPOSED_HEADERS: ""
  CORS_ALLOW_CREDENTIALS: "FALSE"
  CORS_MAX_AGE: "86400"

  # CSP Config
  CSP_ENABLED: "TRUE"
  CSP_REPORT_ONLY: "FALSE"
  CSP_DEFAULT_SRC: "'self'"
  CSP_SCRIPT_SRC: "'self' 'unsafe-inline' https://cdn.socket.io https://static.cloudflareinsights.com"
  CSP_STYLE_SRC: "'self' 'unsafe-inline'"
  CSP_IMG_SRC: "'self' data:"
  CSP_CONNECT_SRC: "'self' wss: ws:"
  CSP_FONT_SRC: "'self'"
  CSP_OBJECT_SRC: "'none'"
  CSP_MEDIA_SRC: "'self' data: https://*.amazonaws.com https://*.cloudfront.net"
  CSP_FRAME_SRC: "'self'"
  CSP_FORM_ACTION: "'self'"
  CSP_FRAME_ANCESTORS: "'self'"
  CSP_BASE_URI: "'self'"
  CSP_UPGRADE_INSECURE_REQUESTS: "FALSE"
  CSP_REPORT_URI: ""

  # CSRF Config
  CSRF_ENABLED: "TRUE"
  CSRF_TIME_LIMIT: ""
  SESSION_COOKIE_NAME: "session"
  CSRF_COOKIE_NAME: "csrf_token"

# Persistent Volume configuration
persistentVolume:
  pvcEnabled: false
  pvEnabled: false
  # PersistentVolume settings for static binding (used if pvEnabled: true)
  volumeName: openalgo-pv
  volumeHandle: openalgo-volume
  claimName: openalgo-test-pvc
  claimNamespace: openalgo
  reclaimPolicy: Retain
  storageClass: longhorn-retain
  size: 1Gi
  accessModes:
    - ReadWriteMany
  mountPath: /data
